/***************************************************************************************
	프로젝트 관리(공용앱)

DROP TABLE ENH_ITEM_TASK_OPN;
DROP TABLE ENH_ITEM_TASK_FILE;
DROP TABLE ENH_ITEM_TASK;
DROP TABLE ENH_ITEM_OPN;
DROP TABLE ENH_ITEM_MOD_LIST;
DROP TABLE ENH_ITEM_MOD_FILE;
DROP TABLE ENH_ITEM_MOD;
DROP TABLE ENH_ITEM_MBR;
DROP TABLE ENH_ITEM_FILE;
DROP TABLE ENH_ITEM;
  
***************************************************************************************/
CREATE TABLE ENH_ITEM
(
	ENHID               NUMBER(8) NOT NULL,
	ENH_NAME            VARCHAR2(1000),
	RGST_DATE          DATE      DEFAULT SYSDATE,
	LAST_UPDT    	   DATE      DEFAULT SYSDATE,
	ENH_SDATE    	   DATE,
	ENH_EDATE           DATE,
	CONTENT            CLOB,
	TENANTID           NUMBER (4),
	USERID             NUMBER(8),
	RGST_NAME          VARCHAR2(1000),
	USER_DISP          VARCHAR2(1000),
	FILE_EXT		   VARCHAR2(8),
	OPN_CNT            NUMBER(8) DEFAULT 0 NOT NULL,
	STATUS			   NUMBER(4) DEFAULT -1 NOT NULL,
	ISVISB			   NUMBER(1) DEFAULT 0 NOT NULL,
	PM_NAME			   VARCHAR2(1000),
	PMID			   NUMBER(8),
	PM_DISP			   VARCHAR2(1000),
	COMPLETE_DATE	   DATE,
	OFCEID			   NUMBER(8),
	OFCE_NAME		   VARCHAR2(1000)
	
)
TABLESPACE R6_DAT     
LOGGING;

CREATE TABLE ENH_ITEM_OPN
(
	OPNID            NUMBER (8) NOT NULL,
	ENHID             NUMBER (8) NOT NULL,
	USERID           NUMBER (8),
	USER_NAME        VARCHAR2 (1000),
	USER_DISP        VARCHAR2 (1000),
	RGST_DATE        DATE DEFAULT SYSDATE,
	CONTENT          VARCHAR2 (4000),
	GID              NUMBER (8),
	RGST_USERID      NUMBER (8)
)
TABLESPACE R6_DAT     
LOGGING;

CREATE TABLE ENH_ITEM_FILE
(
	FILEID   	NUMBER(8)		NOT NULL,
	ENHID      	NUMBER(8)		NOT NULL,
	FILE_NAME   VARCHAR2(500),
	FILE_SIZE   NUMBER(16)      DEFAULT 0 NOT NULL,
	DNLD_CNT    NUMBER(8)       DEFAULT 0 NOT NULL,
	SAVE_CODE   NUMBER(4)    		DEFAULT -1 NOT NULL,
	SAVE_PATH   VARCHAR2(500)
)
TABLESPACE R6_DAT     
LOGGING;

CREATE TABLE ENH_ITEM_MBR
(
	ENHID     	NUMBER(8)		NOT NULL,
	USERID      NUMBER(8)		NOT NULL,
	USER_NAME   VARCHAR2 (1000),
	USER_DISP   VARCHAR2 (1000),
	SEQ_ORDER	NUMBER(8) DEFAULT 0 NOT NULL,
	STATUS		NUMBER(4) DEFAULT -1 NOT NULL,
	ISVISB		NUMBER(1) DEFAULT 0 NOT NULL
)
TABLESPACE R6_DAT     
LOGGING;

CREATE TABLE ENH_ITEM_TASK
(
	TASKID			 NUMBER(8) NOT NULL,
	ENHID              NUMBER(8) NOT NULL,
	RGST_DATE         DATE      DEFAULT SYSDATE,
	LAST_UPDT    	  DATE      DEFAULT SYSDATE,
	TASK_SDATE    	  DATE,
	TASK_EDATE        DATE,
	PLAN_SDATE    	  DATE,
	PLAN_EDATE        DATE,
	TENANTID          NUMBER (4),
	USERID            NUMBER(8),
	USER_NAME         VARCHAR2(1000),
	USER_DISP         VARCHAR2(1000),
	TASK_CODE		  NUMBER(4) NOT NULL,
	TASK              VARCHAR2(1000),
	TASK_CONTENT      CLOB,
	FILE_EXT		  VARCHAR2(8),
	OPN_CNT           NUMBER(8) DEFAULT 0 NOT NULL,
	ISVISB			  NUMBER(1) DEFAULT 0 NOT NULL,
	RESIDE 			  NUMBER(1) DEFAULT 0 NOT NULL,
	PERCENT 		  NUMBER(4) DEFAULT 100 NOT NULL
)
TABLESPACE R6_DAT     
LOGGING;

CREATE TABLE ENH_ITEM_TASK_OPN
(
	OPNID         NUMBER (8) NOT NULL,
	TASKID        NUMBER (8) NOT NULL,
	USERID        NUMBER (8),
	USER_NAME     VARCHAR2 (1000),
	USER_DISP     VARCHAR2 (1000),
	RGST_DATE     DATE DEFAULT SYSDATE,
	CONTENT       VARCHAR2 (4000),
	GID              NUMBER (8),
	RGST_USERID      NUMBER (8)
)
TABLESPACE R6_DAT     
LOGGING;

CREATE TABLE ENH_ITEM_TASK_FILE
(
	FILEID   		NUMBER(8)		NOT NULL,
	TASKID      NUMBER(8)		NOT NULL,
	FILE_NAME   VARCHAR2(500),
	FILE_SIZE   NUMBER(16)      DEFAULT 0 NOT NULL,
	DNLD_CNT    NUMBER(8)       DEFAULT 0 NOT NULL,
	SAVE_CODE   NUMBER(4)    		DEFAULT -1 NOT NULL,
	SAVE_PATH   VARCHAR2(500)
)
TABLESPACE R6_DAT     
LOGGING;

/*********************************************************

	인력관리 시스템 - INDEX 생성

*********************************************************/
CREATE UNIQUE INDEX XPK_ENH_ITEM
ON ENH_ITEM
(
	ENHID ASC
)
TABLESPACE R6_IDX                        
LOGGING                                  
NOCOMPRESS                                                
NOPARALLEL;

CREATE UNIQUE INDEX XPK_ENH_ITEM_FILE
ON ENH_ITEM_FILE
(
	FILEID ASC
)
TABLESPACE R6_IDX                        
LOGGING                                  
NOCOMPRESS                                                
NOPARALLEL;

CREATE UNIQUE INDEX XPK_ENH_ITEM_OPN
ON ENH_ITEM_OPN
(
	OPNID ASC
)
TABLESPACE R6_IDX                        
LOGGING                                  
NOCOMPRESS                                                
NOPARALLEL;

CREATE UNIQUE INDEX XPK_ENH_ITEM_TASK
ON ENH_ITEM_TASK
(
	TASKID ASC
)
TABLESPACE R6_IDX                        
LOGGING                                  
NOCOMPRESS                                                
NOPARALLEL;

CREATE UNIQUE INDEX XPK_ENH_ITEM_TASK_FILE
ON ENH_ITEM_TASK_FILE
(
	FILEID ASC
)
TABLESPACE R6_IDX                        
LOGGING                                  
NOCOMPRESS                                                
NOPARALLEL;

CREATE UNIQUE INDEX XPK_ENH_ITEM_TASK_OPN
ON ENH_ITEM_TASK_OPN
(
	OPNID ASC
)
TABLESPACE R6_IDX                        
LOGGING                                  
NOCOMPRESS                                                
NOPARALLEL;

/*********************************************************

	인력관리 시스템 - 제약조건 (PRIMARY, FOREIGN KEY 생성)

*********************************************************/
ALTER TABLE ENH_ITEM ADD(
	CONSTRAINT XPK_ENH_ITEM PRIMARY KEY (ENHID));
ALTER TABLE ENH_ITEM_TASK ADD(
	CONSTRAINT XPK_ENH_ITEM_TASK PRIMARY KEY (TASKID));
ALTER TABLE ENH_ITEM_FILE ADD(
	CONSTRAINT XPK_ENH_ITEM_FILE PRIMARY KEY (FILEID));
ALTER TABLE ENH_ITEM_OPN ADD(
	CONSTRAINT XPK_ENH_ITEM_OPN PRIMARY KEY (OPNID));
ALTER TABLE ENH_ITEM_TASK_FILE ADD(
	CONSTRAINT XPK_ENH_ITEM_TASK_FILE PRIMARY KEY (FILEID));
ALTER TABLE ENH_ITEM_TASK_OPN ADD(
	CONSTRAINT XPK_ENH_ITEM_TASK_OPN PRIMARY KEY (OPNID));


ALTER TABLE ENH_ITEM_OPN ADD(
	CONSTRAINT ENHITEM_C_OPN FOREIGN KEY (ENHID)
	REFERENCES ENH_ITEM(ENHID) ON DELETE CASCADE);
ALTER TABLE ENH_ITEM_FILE ADD(
	CONSTRAINT ENHITEM_C_FILE FOREIGN KEY (ENHID)
	REFERENCES ENH_ITEM(ENHID) ON DELETE CASCADE);
ALTER TABLE ENH_ITEM_MBR ADD(
	CONSTRAINT ENHITEM_C_MBR FOREIGN KEY (ENHID)
	REFERENCES ENH_ITEM(ENHID) ON DELETE CASCADE);
ALTER TABLE ENH_ITEM_TASK ADD(
	CONSTRAINT ENHITEM_C_TASK FOREIGN KEY (ENHID)
	REFERENCES ENH_ITEM(ENHID) ON DELETE CASCADE);
ALTER TABLE ENH_ITEM_TASK_OPN ADD(
	CONSTRAINT ENHITEMTASK_C_OPN FOREIGN KEY (TASKID)
	REFERENCES ENH_ITEM_TASK(TASKID) ON DELETE CASCADE);
ALTER TABLE ENH_ITEM_TASK_FILE ADD(
	CONSTRAINT ENHITEMTASK_C_FILE FOREIGN KEY (TASKID)
	REFERENCES ENH_ITEM_TASK(TASKID) ON DELETE CASCADE);


/**************************************************
* - 프로젝트관리 고도화
* 작성자 : 이민재
* 작성일시 : 2015/12/22
***************************************************/
CREATE TABLE ENH_ITEM_MOD
(
	MODID            NUMBER (8) NOT NULL,
	ENHID           	 NUMBER (8),
	TITLE            VARCHAR2 (1000),
	ITEM_TITLE       VARCHAR2 (1000),
	CONTENT          CLOB,
	PACKAGE_NAME	 VARCHAR2 (500),
	SEQ_ORDER        NUMBER (4) DEFAULT 0 NOT NULL,
	FILE_EXT         VARCHAR2 (10),
	USERID           NUMBER (8),
	USER_NAME        VARCHAR2 (1000),
	USER_DISP        VARCHAR2 (1000),
	RGST_DATE        DATE DEFAULT SYSDATE,
	LAST_UPDT        DATE DEFAULT SYSDATE,
	LAST_NAME		 VARCHAR2 (1000),
	LAST_DISP        VARCHAR2 (1000),
	LAST_USERID      NUMBER (8),
	ISVISB           NUMBER (1) DEFAULT 0 NOT NULL,
	STATUS           NUMBER (4) DEFAULT -1 NOT NULL
)
TABLESPACE R6_DAT
LOGGING ;

CREATE TABLE ENH_ITEM_MOD_FILE 
(
	FILEID           NUMBER (8) NOT NULL,
	MODID            NUMBER (8) NOT NULL,
	FILE_NAME        VARCHAR2 (500),
	FILE_SIZE        NUMBER (16) DEFAULT 0 NOT NULL,
	DNLD_CNT         NUMBER (8) DEFAULT 0 NOT NULL,
	SAVE_CODE        NUMBER (4) DEFAULT - 1 NOT NULL,
	SAVE_PATH        VARCHAR2 (500)
)
TABLESPACE R6_DAT
LOGGING ;

CREATE TABLE ENH_ITEM_MOD_LIST
(
	TITLE            VARCHAR2 (1000),
	MOD_COUNT        NUMBER (8),
	RGST_DATE        DATE DEFAULT SYSDATE,
	LAST_UPDT        DATE DEFAULT SYSDATE
)
TABLESPACE R6_DAT
LOGGING ;

CREATE UNIQUE INDEX XPK_ENH_ITEM_MOD
ON ENH_ITEM_MOD
(
	MODID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE UNIQUE INDEX XIF_ENHITEMMOD_ENHID
ON ENH_ITEM_MOD
(
	ENHID ASC,
	MODID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIE_ENHITEMMOD_SEQORDER
ON ENH_ITEM_MOD
(
	SEQ_ORDER ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE UNIQUE INDEX XPK_ENH_ITEM_MOD_FILE
ON ENH_ITEM_MOD_FILE
(
	FILEID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE UNIQUE INDEX XIF_ENHITEMMODFILE_TABID
ON ENH_ITEM_MOD_FILE
(
	MODID ASC,
	FILEID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIE_ENHITEMLIST_TITLE
ON ENH_ITEM_MOD_LIST
(
	TITLE ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

ALTER TABLE ENH_ITEM_MOD_FILE ADD(
	CONSTRAINT XPK_ENH_ITEM_MOD_FILE PRIMARY KEY (FILEID));
  
ALTER TABLE ENH_ITEM_MOD ADD(
	CONSTRAINT XPK_ENH_ITEM_MOD PRIMARY KEY (MODID));
  
ALTER TABLE ENH_ITEM_MOD ADD(
	CONSTRAINT ENHITEM_C_MOD FOREIGN KEY (ENHID)
	REFERENCES ENH_ITEM(ENHID) ON DELETE CASCADE);
  
ALTER TABLE ENH_ITEM_MOD_FILE ADD(
	CONSTRAINT ENHITEMMOD_C_FILE FOREIGN KEY (MODID)
	REFERENCES ENH_ITEM_MOD(MODID) ON DELETE CASCADE);
