/*********************************************************

	인력관리 - Sequence 생성

*********************************************************/
-- SELECT 'CREATE SEQUENCE '||SEQUENCE_NAME||' INCREMENT BY 1 START WITH 1 '||DECODE(CYCLE_FLAG, 'Y', 'CYCLE', '')||'; ' Q  FROM USER_SEQUENCES;
CREATE SEQUENCE SQ_ENH_ITEM INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE SQ_ENH_ITEM_OPN INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE SQ_ENH_ITEM_FILE INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE SQ_ENH_ITEM_TASK INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE SQ_ENH_ITEM_TASK_OPN INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE SQ_ENH_ITEM_TASK_FILE INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE SQ_ENH_ITEM_MOD INCREMENT BY 1 START WITH 1 ; 
CREATE SEQUENCE SQ_ENH_ITEM_MOD_FILE INCREMENT BY 1 START WITH 1 ;

