/*********************************************************

	인력관리 - 코멘트 추가

*********************************************************/
/*
select 'COMMENT ON TABLE '||table_name||' IS ''' || comments || ''';' com from user_tab_comments
where table_name not like 'TMP%'
and table_name not like 'MV%'
and table_name not like 'VW%';

select 'COMMENT ON COLUMN '||table_name||'.'||column_name||' IS ''' || comments || ''';' comm
from user_col_comments where table_name not like 'TMP%'
and table_name not like 'MV%'
and table_name not like 'VW%';
*/

COMMENT ON TABLE ENH_ITEM 				IS '프로젝트관리';
COMMENT ON TABLE ENH_ITEM_MBR			IS '프로젝트팀원';
COMMENT ON TABLE ENH_ITEM_TASK 			IS '프로젝트팀원업무';
COMMENT ON TABLE ENH_ITEM_FILE 			IS '프로젝트첨부파일';
COMMENT ON TABLE ENH_ITEM_OPN			IS '프로젝트의견';
COMMENT ON TABLE ENH_ITEM_TASK_FILE		IS '프로젝트업무첨부파일';
COMMENT ON TABLE ENH_ITEM_TASK_OPN 		IS '프로젝트업무의견';
COMMENT ON TABLE ENH_ITEM_MOD 			IS '프로젝트모듈';
COMMENT ON TABLE ENH_ITEM_MOD_FILE 		IS '프로젝트모듈첨부파일';
COMMENT ON TABLE ENH_ITEM_MOD_LIST 		IS '프로젝트모듈목록';

COMMENT ON COLUMN ENH_ITEM.ENHID			IS '프로젝트일련번호';
COMMENT ON COLUMN ENH_ITEM.ENH_NAME		IS '프로젝트이름';
COMMENT ON COLUMN ENH_ITEM.RGST_DATE		IS '등록일시';
COMMENT ON COLUMN ENH_ITEM.LAST_UPDT		IS '마지막수정일시';
COMMENT ON COLUMN ENH_ITEM.ENH_SDATE		IS '프로젝트시작일';
COMMENT ON COLUMN ENH_ITEM.ENH_EDATE		IS '프로젝트완료일';
COMMENT ON COLUMN ENH_ITEM.CONTENT		IS '프로젝트내용';
COMMENT ON COLUMN ENH_ITEM.USERID		IS '등록자일련번호';
COMMENT ON COLUMN ENH_ITEM.RGST_NAME		IS '등록자이름';
COMMENT ON COLUMN ENH_ITEM.USER_DISP		IS '등록자상세이름';
COMMENT ON COLUMN ENH_ITEM.FILE_EXT		IS '확장자';
COMMENT ON COLUMN ENH_ITEM.OPN_CNT		IS '의견수';
COMMENT ON COLUMN ENH_ITEM.STATUS		IS '프로젝트상태';
COMMENT ON COLUMN ENH_ITEM.ISVISB		IS '보임여부';
COMMENT ON COLUMN ENH_ITEM.PM_NAME		IS 'PM이름';
COMMENT ON COLUMN ENH_ITEM.PMID			IS 'PM일련번호';
COMMENT ON COLUMN ENH_ITEM.PM_DISP		IS 'PM상세이름';
COMMENT ON COLUMN ENH_ITEM.COMPLETE_DATE	IS '완료일시';
COMMENT ON COLUMN ENH_ITEM.OFCEID		IS '직장일련번호';
COMMENT ON COLUMN ENH_ITEM.OFCE_NAME		IS '직장명';
COMMENT ON COLUMN ENH_ITEM.TENANTID		IS '회사별ID';

COMMENT ON COLUMN ENH_ITEM_OPN.OPNID		IS '의견일련번호';
COMMENT ON COLUMN ENH_ITEM_OPN.ENHID		IS '프로젝트일련번호';
COMMENT ON COLUMN ENH_ITEM_OPN.USERID	IS '사용자일련번호';
COMMENT ON COLUMN ENH_ITEM_OPN.USER_NAME	IS '사용자이름';
COMMENT ON COLUMN ENH_ITEM_OPN.USER_DISP	IS '사용자상세이름';
COMMENT ON COLUMN ENH_ITEM_OPN.RGST_DATE	IS '등록일시';
COMMENT ON COLUMN ENH_ITEM_OPN.CONTENT	IS '내용';

COMMENT ON COLUMN ENH_ITEM_FILE.FILEID		IS '파일일련번호';
COMMENT ON COLUMN ENH_ITEM_FILE.ENHID			IS '프로젝트일련번호';
COMMENT ON COLUMN ENH_ITEM_FILE.FILE_NAME	IS '파일이름';
COMMENT ON COLUMN ENH_ITEM_FILE.FILE_SIZE	IS '파일사이즈';
COMMENT ON COLUMN ENH_ITEM_FILE.DNLD_CNT		IS '다운로드횟수';
COMMENT ON COLUMN ENH_ITEM_FILE.SAVE_CODE	IS '저장코드';
COMMENT ON COLUMN ENH_ITEM_FILE.SAVE_PATH	IS '저장경로';

COMMENT ON COLUMN ENH_ITEM_MBR.ENHID			IS '프로젝트일련번호';
COMMENT ON COLUMN ENH_ITEM_MBR.USERID		IS '사용자일련번호';
COMMENT ON COLUMN ENH_ITEM_MBR.USER_NAME		IS '사용자이름';
COMMENT ON COLUMN ENH_ITEM_MBR.USER_DISP		IS '사용자상세이름';
COMMENT ON COLUMN ENH_ITEM_MBR.SEQ_ORDER 	IS '그룹순차부여번호';
COMMENT ON COLUMN ENH_ITEM_MBR.STATUS 		IS '상태';
COMMENT ON COLUMN ENH_ITEM_MBR.ISVISB 		IS '보임여부';

COMMENT ON COLUMN ENH_ITEM_TASK.TASKID		IS '담당업무일련번호';
COMMENT ON COLUMN ENH_ITEM_TASK.ENHID			IS '프로젝트일련번호';
COMMENT ON COLUMN ENH_ITEM_TASK.RGST_DATE	IS '등록일시';
COMMENT ON COLUMN ENH_ITEM_TASK.LAST_UPDT	IS '마지막수정일시';
COMMENT ON COLUMN ENH_ITEM_TASK.TASK_SDATE	IS '업무시작일';
COMMENT ON COLUMN ENH_ITEM_TASK.TASK_EDATE	IS '업무완료일';
COMMENT ON COLUMN ENH_ITEM_TASK.USERID		IS '사용자일련번호';
COMMENT ON COLUMN ENH_ITEM_TASK.USER_NAME	IS '사용자이름';
COMMENT ON COLUMN ENH_ITEM_TASK.USER_DISP	IS '사용자상세이름';
COMMENT ON COLUMN ENH_ITEM_TASK.TASK_CODE	IS '업무역할코드';
COMMENT ON COLUMN ENH_ITEM_TASK.TASK  		IS '업무';
COMMENT ON COLUMN ENH_ITEM_TASK.TASK_CONTENT	IS '업무내용';
COMMENT ON COLUMN ENH_ITEM_TASK.FILE_EXT		IS '확장자';
COMMENT ON COLUMN ENH_ITEM_TASK.OPN_CNT		IS '의견수';
COMMENT ON COLUMN ENH_ITEM_TASK.PLAN_SDATE	IS '업무계획시작일';
COMMENT ON COLUMN ENH_ITEM_TASK.PLAN_EDATE	IS '업무계획완료일';
COMMENT ON COLUMN ENH_ITEM_TASK.ISVISB		IS '보임여부';
COMMENT ON COLUMN ENH_ITEM_TASK.TENANTID		IS '회사별ID';

COMMENT ON COLUMN ENH_ITEM_TASK_OPN.OPNID	IS '의견일련번호';
COMMENT ON COLUMN ENH_ITEM_TASK_OPN.TASKID	IS '담당업무일련번호';
COMMENT ON COLUMN ENH_ITEM_TASK_OPN.USERID		IS '사용자일련번호';
COMMENT ON COLUMN ENH_ITEM_TASK_OPN.USER_NAME	IS '사용자이름';
COMMENT ON COLUMN ENH_ITEM_TASK_OPN.USER_DISP	IS '사용자상세이름';
COMMENT ON COLUMN ENH_ITEM_TASK_OPN.RGST_DATE	IS '등록일시';
COMMENT ON COLUMN ENH_ITEM_TASK_OPN.CONTENT		IS '내용';

COMMENT ON COLUMN ENH_ITEM_TASK_FILE.FILEID			IS '파일일련번호';
COMMENT ON COLUMN ENH_ITEM_TASK_FILE.TASKID			IS '담당업무일련번호';
COMMENT ON COLUMN ENH_ITEM_TASK_FILE.FILE_NAME		IS '파일이름';
COMMENT ON COLUMN ENH_ITEM_TASK_FILE.FILE_SIZE		IS '파일사이즈';
COMMENT ON COLUMN ENH_ITEM_TASK_FILE.DNLD_CNT		IS '다운로드횟수';
COMMENT ON COLUMN ENH_ITEM_TASK_FILE.SAVE_CODE		IS '저장코드';
COMMENT ON COLUMN ENH_ITEM_TASK_FILE.SAVE_PATH		IS '저장경로';
COMMENT ON COLUMN ENH_ITEM_TASK.RESIDE				IS '상주여부';  /**  0:상주,1:비상주,2.일부상주 **/
COMMENT ON COLUMN ENH_ITEM_TASK.PERCENT				IS '투입가중치';  /** Default 100% **/

COMMENT ON COLUMN ENH_ITEM_MOD.MODID						IS '모듈일련번호';
COMMENT ON COLUMN ENH_ITEM_MOD.ENHID						IS '프로젝트일련번호';
COMMENT ON COLUMN ENH_ITEM_MOD.TITLE						IS '제목';
COMMENT ON COLUMN ENH_ITEM_MOD.ITEM_TITLE				IS '본글제목';
COMMENT ON COLUMN ENH_ITEM_MOD.CONTENT					IS '내용';
COMMENT ON COLUMN ENH_ITEM_MOD.PACKAGE_NAME				IS '패키지명';
COMMENT ON COLUMN ENH_ITEM_MOD.SEQ_ORDER					IS '그룹순차번호';
COMMENT ON COLUMN ENH_ITEM_MOD.FILE_EXT					IS '확장자';
COMMENT ON COLUMN ENH_ITEM_MOD.USERID					IS '사용자일련번호';
COMMENT ON COLUMN ENH_ITEM_MOD.USER_NAME					IS '사용자이름';
COMMENT ON COLUMN ENH_ITEM_MOD.USER_DISP					IS '사용자상세이름';
COMMENT ON COLUMN ENH_ITEM_MOD.RGST_DATE					IS '등록일자';
COMMENT ON COLUMN ENH_ITEM_MOD.LAST_UPDT					IS '마지막수정일시';
COMMENT ON COLUMN ENH_ITEM_MOD.LAST_NAME					IS '수정자이름';
COMMENT ON COLUMN ENH_ITEM_MOD.LAST_DISP					IS '수정자상세이름';
COMMENT ON COLUMN ENH_ITEM_MOD.LAST_USERID				IS '수정자일련번호';
COMMENT ON COLUMN ENH_ITEM_MOD.ISVISB					IS '보임여부';
COMMENT ON COLUMN ENH_ITEM_MOD.STATUS					IS '상태';
COMMENT ON COLUMN ENH_ITEM_MOD_FILE.FILEID				IS '파일일련번호';
COMMENT ON COLUMN ENH_ITEM_MOD_FILE.MODID				IS '모듈일련번호';
COMMENT ON COLUMN ENH_ITEM_MOD_FILE.FILE_NAME			IS '파일이름';
COMMENT ON COLUMN ENH_ITEM_MOD_FILE.FILE_SIZE			IS '파일사이즈';
COMMENT ON COLUMN ENH_ITEM_MOD_FILE.DNLD_CNT				IS '다운로드횟수';
COMMENT ON COLUMN ENH_ITEM_MOD_FILE.SAVE_CODE			IS '저장코드';
COMMENT ON COLUMN ENH_ITEM_MOD_FILE.SAVE_PATH			IS '저장경로';
COMMENT ON COLUMN ENH_ITEM_MOD_LIST.TITLE 				IS '제목'; 
COMMENT ON COLUMN ENH_ITEM_MOD_LIST.MOD_COUNT 			IS '모듈갯수'; 
COMMENT ON COLUMN ENH_ITEM_MOD_LIST.RGST_DATE 			IS '등록일자'; 
COMMENT ON COLUMN ENH_ITEM_MOD_LIST.LAST_UPDT 			IS '마지막수정일시'; 