/******************************************************************
	위키북 Table   
	DROP TABLE WIKIBOOK_OPN ;
	DROP TABLE WIKIBOOK_SCRT ;
	DROP TABLE WIKIBOOK_CATH ;
	DROP TABLE WIKIBOOK_COMMENT ;
	DROP TABLE WIKIBOOK_FVRT ;
	DROP TABLE WIKIBOOK_HISTORY ;
	DROP TABLE WIKIBOOK_SYMPATHY ;
	DROP TABLE WIKIBOOK_ITEM_FILE ;
	DROP TABLE WIKIBOOK_ITEM_READ ;
	DROP TABLE WIKIBOOK_ITEM_TAG ;
	DROP TABLE WIKIBOOK_ITEM ;
	DROP TABLE WIKIBOOK ;
******************************************************************/

CREATE TABLE WIKIBOOK 
(
	MODULEID         NUMBER (8),
	CLASSID          NUMBER (8),
	APPID           NUMBER (8),
	TENANTID         NUMBER (4),
	BOOKID           NUMBER (8) NOT NULL,
	TITLE            VARCHAR2 (1000),
	KMID             NUMBER (8),
	LEVEL1           NUMBER (8),
	LEVEL2           NUMBER (8),
	LEVEL3           NUMBER (8),
	LEVEL4           NUMBER (8),
	APLY_DATE        DATE,
	RGST_DATE        DATE,
	LAST_UPDT        DATE,
	USERID           NUMBER (8),
	USER_NAME        VARCHAR2 (1000),
	USER_DISP        VARCHAR2 (1000),
	STATUS           NUMBER (4),
	ISVISB           NUMBER (1) DEFAULT 0 NOT NULL,
	SCRT_LEVEL       NUMBER (4),
	ITEM_CNT         NUMBER (8) DEFAULT 0 NOT NULL,
	VISIT_CNT        NUMBER (8) DEFAULT 0 NOT NULL,
	PICT_SAVE_CODE   NUMBER (4),
	PICT_SAVE_PATH   VARCHAR2 (500),
	BOOK_INTRO       VARCHAR2 (500),
	CATH_CNT         NUMBER (8),
	THUMB_SAVE_CODE  NUMBER (4) DEFAULT - 1,
	THUMB_SAVE_PATH  VARCHAR2 (500),
	UPDT_USERID      NUMBER (8),
	UPDT_NAME        VARCHAR2 (1000),
	OPN_CNT         NUMBER (8) DEFAULT 0 NOT NULL,
	SPID             NUMBER (8),
	ISMOBILE         NUMBER (1) DEFAULT 0 NOT NULL,
	SYMPATHY_CNT     NUMBER (8) DEFAULT 0 NOT NULL,
	READ_CNT         NUMBER (8) DEFAULT 0 NOT NULL
)
TABLESPACE R6_DAT
LOGGING ;

/******************************************************************
	위키북 의견 Table   
    WIKIBOOK_OPN
******************************************************************/
CREATE TABLE WIKIBOOK_OPN 
(
	OPNID            NUMBER (8) NOT NULL,
	BOOKID           NUMBER (8) NOT NULL,
	USERID           NUMBER (8),
	USER_NAME        VARCHAR2 (1000),
	RGST_DATE        DATE DEFAULT SYSDATE,
	USER_DISP        VARCHAR2 (1000),
	CONTENT          VARCHAR2 (4000),
	GID              NUMBER (8) NOT NULL
)
TABLESPACE R6_DAT
LOGGING ;

/******************************************************************
	위키북 보안 Table   
    WIKIBOOK_SCRT
******************************************************************/
CREATE TABLE WIKIBOOK_SCRT 
(
	XID          NUMBER (17) NOT NULL,
	BOOKID           NUMBER (8) NOT NULL,
	SEQ_ORDER        NUMBER (8) DEFAULT 0 NOT NULL,
	TITLE            VARCHAR2 (1000),
	ISVISB           NUMBER (1) DEFAULT 0 NOT NULL,
	ISCOMP           NUMBER (1) DEFAULT 0 NOT NULL
)
TABLESPACE R6_DAT
LOGGING ;

/******************************************************************
	위키북 공동저자 Table   
    WIKIBOOK_CATH
******************************************************************/
CREATE TABLE WIKIBOOK_CATH
(
	BOOKID           NUMBER (8) NOT NULL,
	SEQ_ORDER        NUMBER (8) DEFAULT 0 NOT NULL,
	USERID           NUMBER (8) NOT NULL,
	USER_NAME        VARCHAR2 (1000),
	USER_DISP        VARCHAR2 (1000)
)
TABLESPACE R6_DAT
LOGGING ;

/******************************************************************
	위키북  사유(승인/반려) Table   
    WIKIBOOK_COMMENT
******************************************************************/
CREATE TABLE WIKIBOOK_COMMENT 
(
	COMMENTID        NUMBER (8) NOT NULL,
	BOOKID           NUMBER (8),
	USERID           NUMBER (8),
	USER_NAME        VARCHAR2 (1000),
	USER_DISP        VARCHAR2 (1000),
	COMMENT_CODE     NUMBER (4) DEFAULT 0 NOT NULL,
	RGST_DATE        DATE DEFAULT sysdate,
	CONTENT          VARCHAR2 (4000)
)
TABLESPACE R6_DAT
LOGGING ;

/******************************************************************
	위키북  공감   
    WIKIBOOK_SYMPATHY
******************************************************************/

CREATE TABLE  WIKIBOOK_SYMPATHY 
(
	BOOKID           NUMBER (8) NOT NULL,
	USERID           NUMBER (8) NOT NULL,
	USER_NAME        VARCHAR2 (1000),
	USER_DISP        VARCHAR2 (1000),
	SYMP_TYPE        NUMBER (4) DEFAULT -1 NOT NULL,
	INST_DATE        DATE DEFAULT SYSDATE NOT NULL
)
TABLESPACE R6_DAT
LOGGING ;

/******************************************************************
	위키글  Table   
    WIKIBOOK_ITEM
******************************************************************/
CREATE TABLE WIKIBOOK_ITEM 
(
	ITEMID           NUMBER (8) NOT NULL,
	BOOKID           NUMBER (8),
	GID              NUMBER (8) NOT NULL,
    ROOTID           NUMBER (8),
	PID              NUMBER (8),
	POS              NUMBER (8) DEFAULT - 1 NOT NULL,
	SORT             NUMBER (8) DEFAULT 0 NOT NULL,
	VRSN_NUM         NUMBER (8) DEFAULT 1 NOT NULL,
	TITLE            VARCHAR2 (1000),
	USERID           NUMBER (8),
	USER_NAME        VARCHAR2 (1000),
	USER_DISP        VARCHAR2 (1000),
	VRSN_USERID      NUMBER (8),
	VRSN_NAME        VARCHAR2 (1000),
	VRSN_DISP        VARCHAR2 (1000),
	RGST_DATE        DATE,
	CONTENT          CLOB,
	FILE_EXT         VARCHAR2 (8),
	READ_CNT         NUMBER (8) DEFAULT 0 NOT NULL,
	OPN_CNT          NUMBER (8) DEFAULT 0,
	ISVISB           NUMBER (1) DEFAULT 0 NOT NULL,
	INST_DATE        DATE DEFAULT SYSDATE NOT NULL,
	STATUS           NUMBER (4) DEFAULT - 1 NOT NULL,
	FLAG_CODE        NUMBER (16) DEFAULT 0 NOT NULL,
	LAST_UPDT        DATE DEFAULT SYSDATE
)
TABLESPACE R6_DAT
LOGGING ;

/******************************************************************
	위키글 첨부파일 Table   
    WIKIBOOK_ITEM_FILE
******************************************************************/
CREATE TABLE WIKIBOOK_ITEM_FILE 
(
	FILEID           NUMBER (8) NOT NULL,
	ITEMID           NUMBER (8) NOT NULL,
	FILE_NAME        VARCHAR2 (500),
	FILE_SIZE        NUMBER (16) DEFAULT 0 NOT NULL,
	DNLD_CNT         NUMBER (8) DEFAULT 0 NOT NULL,
	SAVE_CODE        NUMBER (4) DEFAULT - 1 NOT NULL,
	SAVE_PATH        VARCHAR2 (500)
)
TABLESPACE R6_DAT
LOGGING ;

/******************************************************************
	위키글 조회로그 Table   
    WIKIBOOK_ITEM_READ
******************************************************************/
CREATE TABLE WIKIBOOK_ITEM_READ 
(
	ITEMID           NUMBER (8) NOT NULL,
	USERID           NUMBER (8) NOT NULL,
	CMD_CODE         NUMBER (4) DEFAULT - 1 NOT NULL,
	INST_DATE        DATE DEFAULT SYSDATE NOT NULL,
	USER_NAME        VARCHAR2 (1000),
	USER_DISP        VARCHAR2 (1000),
	STAT_FLAG        NUMBER (1) DEFAULT 0 NOT NULL
)
TABLESPACE R6_DAT
LOGGING ;

/******************************************************************
	위키글 태그 Table   
    WIKIBOOK_ITEM_TAG
******************************************************************/
CREATE TABLE WIKIBOOK_ITEM_TAG 
(
	ITEMID           NUMBER (8) NOT NULL,
	TAG              VARCHAR2 (100),
	ITEM_DATE        DATE,
	SEQ_ORDER        NUMBER (8) DEFAULT 0 NOT NULL
)
TABLESPACE R6_DAT
LOGGING ;

/******************************************************************
	위키북 저자 변경 이력 Table   
    WIKIBOOK_HISTORY
******************************************************************/
CREATE TABLE WIKIBOOK_HISTORY
(
	BOOKID              NUMBER (8) not null,
	NEW_USERID          NUMBER (8) ,
	NEW_USERNAME        VARCHAR2 (1000),
	NEW_USERDISP        VARCHAR2 (1000),
	OLD_USERID          NUMBER (8),
	OLD_USERNAME        VARCHAR2 (1000),
	OLD_USERDISP        VARCHAR2 (1000),
	RGST_USERID         NUMBER (8),
	RGST_USERNAME       VARCHAR2 (1000),
	INST_DATE           DATE DEFAULT SYSDATE NOT NULL
)
TABLESPACE R6_DAT
LOGGING ;

/******************************************************************
	위키북 즐겨찾기 Table   
    WIKIBOOK_FVRT
******************************************************************/
CREATE TABLE WIKIBOOK_FVRT
(
	FVRTID          NUMBER (8) not null,
	BOOKID          NUMBER (8) not null,
	USERID          NUMBER (8) ,
	RGST_DATE       DATE DEFAULT SYSDATE NOT NULL
)
TABLESPACE R6_DAT
LOGGING ;

CREATE UNIQUE INDEX XPK_WIKIBOOK 
ON WIKIBOOK
(
	BOOKID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIF_WIKIBOOK_KMID 
ON WIKIBOOK
(
	KMID ASC,
	STATUS ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIF_WIKIBOOK_MODULEID
ON WIKIBOOK
(
		MODULEID ASC,
		APPID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIF_WIKIBOOK_TENANTID 
ON WIKIBOOK
(
	TENANTID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIF_WIKIBOOK_CLASSID 
ON WIKIBOOK
(
	CLASSID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE UNIQUE INDEX XPK_WIKIBOOK_OPN 
ON WIKIBOOK_OPN 
(
	OPNID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE UNIQUE INDEX XIF_WIKIBOOKOPN_GID 
ON WIKIBOOK_OPN 
(
	BOOKID ASC,
	GID ASC,
	OPNID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE UNIQUE INDEX XIF_WIKIBOOKWOPN_BOOKID 
ON WIKIBOOK_OPN 
(
	BOOKID ASC,
	OPNID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIE_WIKIBOOKSCRT_XID 
ON WIKIBOOK_SCRT
(
	BOOKID ASC,
	XID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIF_WIKIBOOKSCRT_ITEMID
ON WIKIBOOK_SCRT
(
	BOOKID ASC,
	SEQ_ORDER ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE UNIQUE INDEX XIF_WIKIBOOKCATH_ITEMID 
ON WIKIBOOK_CATH
(
	BOOKID ASC,
	SEQ_ORDER ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE UNIQUE INDEX XIF_WIKIBOOKCOMMENT_BOOKID 
ON WIKIBOOK_COMMENT
(
	BOOKID ASC,
	COMMENTID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE UNIQUE INDEX XPK_WIKIBOOK_COMMENT 
ON WIKIBOOK_COMMENT
(
	COMMENTID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE UNIQUE INDEX XPK_WIKIBOOK_SYMPATHY 
ON WIKIBOOK_SYMPATHY
(
	BOOKID ASC,
	USERID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIF_WIKIBOOKITEM_BOOKID 
ON WIKIBOOK_ITEM
(
    BOOKID ASC,
	ISVISB ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIF_WIKIBOOKITEM_GID 
ON WIKIBOOK_ITEM
(
	GID ASC
)TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIF_WIKIBOOKITEM_PID 
ON WIKIBOOK_ITEM
(
	PID ASC
)TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIF_WIKIBOOKITEM_USERID 
ON WIKIBOOK_ITEM
(
	USERID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE UNIQUE INDEX XPK_WIKIBOOK_ITEM
ON WIKIBOOK_ITEM
(
	ITEMID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE UNIQUE INDEX XPK_WIKIBOOK_ITEM_FILE
ON WIKIBOOK_ITEM_FILE
(
	FILEID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE UNIQUE INDEX XIF_WIKIBOOKITEMFILE_ITEMID 
ON WIKIBOOK_ITEM_FILE
(
	ITEMID ASC,
	FILEID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIE_WIKIBOOKITEMREAD_ITEMID 
ON WIKIBOOK_ITEM_READ
(
	CMD_CODE ASC,
	ITEMID ASC,
	INST_DATE ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIF_WIKIBOOKITEMREAD_ITEMID 
ON WIKIBOOK_ITEM_READ
(
	ITEMID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIE_WIKIBOOKITEMTAG_TAG 
ON WIKIBOOK_ITEM_TAG 
(
	UPPER ("TAG") ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIE_WIKIBOOKITEMTAG_ITEMID 
ON WIKIBOOK_ITEM_TAG 
(
	ITEMID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

ALTER TABLE WIKIBOOK ADD(
	CONSTRAINT XPK_WIKIBOOK PRIMARY KEY (BOOKID));
	
ALTER TABLE WIKIBOOK ADD(
	CONSTRAINT TENANT_R_WIKIBOOK FOREIGN KEY (TENANTID)
	REFERENCES TENANT(TENANTID) );

ALTER TABLE WIKIBOOK ADD(
	CONSTRAINT WBCLASS_R_WIKIBOOK FOREIGN KEY (CLASSID)
	REFERENCES WB_CLASS(CLASSID) );

ALTER TABLE WIKIBOOK ADD(
	CONSTRAINT WBMODULE_R_WIKIBOOK FOREIGN KEY (MODULEID)
	REFERENCES WB_MODULE(MODULEID) );
	
ALTER TABLE WIKIBOOK ADD(
	CONSTRAINT HRUSER_R_WIKIBOOK FOREIGN KEY (USERID)
	REFERENCES HR_USER(USERID) );
	
ALTER TABLE WIKIBOOK ADD(
	CONSTRAINT HRUSER_R_WIKIBOOKUPDT FOREIGN KEY (UPDT_USERID)
	REFERENCES HR_USER(USERID) );

ALTER TABLE WIKIBOOK ADD(
	CONSTRAINT KM_R_WIKIBOOK FOREIGN KEY (KMID)
	REFERENCES KM(KMID) );

ALTER TABLE WIKIBOOK_OPN ADD(
	CONSTRAINT XPK_WIKIBOOK_OPN PRIMARY KEY (OPNID));
	
ALTER TABLE WIKIBOOK_OPN ADD(
	CONSTRAINT HRUSER_R_WIKIBOOKOPN FOREIGN KEY (USERID)
	REFERENCES HR_USER(USERID) );

ALTER TABLE WIKIBOOK_OPN ADD(
	CONSTRAINT WIKIBOOK_C_OPN FOREIGN KEY (BOOKID)
	REFERENCES WIKIBOOK (BOOKID) ON DELETE CASCADE);

ALTER TABLE WIKIBOOK_SCRT ADD(
	CONSTRAINT WIKIBOOK_C_SCRT FOREIGN KEY (BOOKID)
	REFERENCES WIKIBOOK (BOOKID) ON DELETE CASCADE);

ALTER TABLE WIKIBOOK_CATH ADD(
	CONSTRAINT WIKIBOOK_C_CATH FOREIGN KEY (BOOKID)
	REFERENCES WIKIBOOK (BOOKID) ON DELETE CASCADE);

ALTER TABLE WIKIBOOK_CATH ADD(
	CONSTRAINT HRUSER_R_WIKIBOOKCATH FOREIGN KEY (USERID)
	REFERENCES HR_USER(USERID) );

ALTER TABLE WIKIBOOK_COMMENT ADD(
	CONSTRAINT XPK_WIKIBOOK_COMMENT PRIMARY KEY (COMMENTID));
	
ALTER TABLE WIKIBOOK_COMMENT ADD(
	CONSTRAINT HRUSER_R_WIKIBOOKCOMMENT FOREIGN KEY (USERID)
	REFERENCES HR_USER(USERID) );

ALTER TABLE WIKIBOOK_SYMPATHY ADD(
	CONSTRAINT XPK_WIKIBOOK_SYMPATHY PRIMARY KEY (BOOKID, USERID));

ALTER TABLE WIKIBOOK_SYMPATHY ADD(
	CONSTRAINT WIKIBOOK_C_SYMPATHY FOREIGN KEY (BOOKID)
	REFERENCES WIKIBOOK(BOOKID) ON DELETE CASCADE);

ALTER TABLE WIKIBOOK_ITEM ADD(
	CONSTRAINT XPK_WIKIBOOK_ITEM PRIMARY KEY (ITEMID));
    
ALTER TABLE WIKIBOOK_ITEM 	ADD(
	CONSTRAINT WIKIBOOKITEM_R FOREIGN KEY (GID) REFERENCES WIKIBOOK_ITEM (ITEMID)) ;

ALTER TABLE WIKIBOOK_ITEM 	ADD(
	CONSTRAINT WIKIBOOK_C_ITEM FOREIGN KEY (BOOKID) REFERENCES WIKIBOOK (BOOKID)) ;
	
ALTER TABLE WIKIBOOK_ITEM ADD(
	CONSTRAINT HRUSER_R_WIKIBOOKITEM FOREIGN KEY (USERID)
	REFERENCES HR_USER(USERID) );
	
ALTER TABLE WIKIBOOK_ITEM ADD(
	CONSTRAINT HRUSER_R_WIKIBOOKITEMVRSN FOREIGN KEY (VRSN_USERID)
	REFERENCES HR_USER(USERID) );

ALTER TABLE WIKIBOOK_ITEM_FILE ADD(
	CONSTRAINT XPK_WIKIBOOK_ITEM_FILE PRIMARY KEY (FILEID));

ALTER TABLE WIKIBOOK_ITEM_FILE 	ADD(
	CONSTRAINT WIKIBOOKITEM_C_FILE FOREIGN KEY (ITEMID) REFERENCES WIKIBOOK_ITEM (ITEMID)
	ON DELETE CASCADE) ;

ALTER TABLE WIKIBOOK_ITEM_READ 	ADD(
	CONSTRAINT WIKIBOOKITEM_C_READ FOREIGN KEY (ITEMID) REFERENCES WIKIBOOK_ITEM (ITEMID)
	ON DELETE CASCADE) ;

ALTER TABLE WIKIBOOK_ITEM_TAG 	ADD(
	CONSTRAINT WIKIBOOKITEM_C_TAG FOREIGN KEY (ITEMID) REFERENCES WIKIBOOK_ITEM (ITEMID)
	ON DELETE CASCADE) ;

ALTER TABLE WIKIBOOK_FVRT ADD(
	CONSTRAINT XPK_WIKIBOOK_FVRT PRIMARY KEY (FVRTID));
	
ALTER TABLE WIKIBOOK_FVRT ADD(
	CONSTRAINT WIKIBOOK_C_FVRT FOREIGN KEY (BOOKID)
	REFERENCES WIKIBOOK(BOOKID) ON DELETE CASCADE);
	
ALTER TABLE WIKIBOOK_HISTORY ADD(
	CONSTRAINT WIKIBOOK_C_HISTORY FOREIGN KEY (BOOKID)
	REFERENCES WIKIBOOK(BOOKID) ON DELETE CASCADE);
	
/******************************************************************
	위키북 태그 Table   
    WIKIBOOK_TAG
    
    DROP TABLE WIKIBOOK_TAG;
******************************************************************/
CREATE TABLE WIKIBOOK_TAG 
(
	BOOKID           NUMBER (8) NOT NULL,
	TAG              VARCHAR2 (100),
	ITEM_DATE        DATE,
	SEQ_ORDER        NUMBER (8) DEFAULT 0 NOT NULL,
	ISVISB			 NUMBER (1) DEFAULT 0 NOT NULL
)
TABLESPACE R6_DAT
LOGGING ;

CREATE INDEX XIE_WIKIBOOKTAG_ISVISB 
ON WIKIBOOK_TAG
(
	ISVISB ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIE_WIKIBOOKTAG_TAG
ON WIKIBOOK_TAG 
(
	UPPER ("TAG") ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIE_WIKIBOOKTAG_BOOKID
ON WIKIBOOK_TAG 
(
	BOOKID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

ALTER TABLE WIKIBOOK_TAG	ADD(
	CONSTRAINT WIKIBOOK_C_TAG FOREIGN KEY (BOOKID) REFERENCES WIKIBOOK (BOOKID)
	ON DELETE CASCADE) ;
	
/******************************************************************
	위키북 조회 Table   
    WIKIBOOK_READ
    
    DROP TABLE WIKIBOOK_READ;
******************************************************************/
CREATE TABLE WIKIBOOK_READ 
(
	BOOKID      NUMBER (8) NOT NULL,
	USERID      NUMBER (8) NOT NULL,
	CMD_CODE    NUMBER (10) DEFAULT - 1 NOT NULL,
	INST_DATE   DATE DEFAULT SYSDATE NOT NULL,
	USER_NAME   VARCHAR2 (1000),
	USER_DISP   VARCHAR2 (1000),
	STAT_FLAG   NUMBER (1) DEFAULT 0 NOT NULL
)
TABLESPACE R6_DAT;

CREATE INDEX XIE_WIKIBOOKREAD_BOOKID
ON WIKIBOOK_READ
(
	CMD_CODE ASC,
	BOOKID ASC,
	INST_DATE ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIF_WIKIBOOKREAD_BOOKID 
ON WIKIBOOK_READ
(
	BOOKID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

ALTER TABLE WIKIBOOK_READ ADD(
	CONSTRAINT WIKIBOOK_C_READ FOREIGN KEY (BOOKID)
	REFERENCES WIKIBOOK(BOOKID) ON DELETE CASCADE);
	
/******************************************************************
	위키북 목차 관련자료 Table   
    WIKIBOOK_ITEM_RFRN
    
    DROP TABLE WIKIBOOK_ITEM_RFRN;
******************************************************************/
CREATE TABLE WIKIBOOK_ITEM_RFRN 
(
	RFRNID       NUMBER (8) NOT NULL,
	ITEMID       NUMBER (8) NOT NULL,
	TITLE        VARCHAR2 (1000),
	USERID       NUMBER (8),
	USER_NAME    VARCHAR2 (1000),
	MODULEID     NUMBER (8),
	CLASSID      NUMBER (8),
	SPID         NUMBER (8),
	RFRN_QUERY   VARCHAR2 (500),
	APPID        NUMBER (8),
	EXTR_APPID   NUMBER (8)
)
TABLESPACE R6_DAT;

CREATE UNIQUE INDEX XIF_WIKIBOOKITEMRFRN_ITEMID 
ON WIKIBOOK_ITEM_RFRN
(
	ITEMID ASC,
	RFRNID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

CREATE INDEX XIF_WIKIBOOKITEMRFRN_USERID 
ON WIKIBOOK_ITEM_RFRN
(
	USERID ASC
)
TABLESPACE R6_IDX
LOGGING
NOCOMPRESS
NOPARALLEL ;

ALTER TABLE WIKIBOOK_ITEM_RFRN ADD(
	CONSTRAINT XPK_WIKIBOOK_ITEM_RFRN PRIMARY KEY (RFRNID));

ALTER TABLE WIKIBOOK_ITEM_RFRN ADD(
	CONSTRAINT WIKIBOOKITEM_C_RFRN FOREIGN KEY (ITEMID)
	REFERENCES WIKIBOOK_ITEM(ITEMID) ON DELETE CASCADE);

ALTER TABLE WIKIBOOK_ITEM_RFRN ADD(
	CONSTRAINT HRUSER_R_WIKIBOOKITEMRFRN FOREIGN KEY (USERID)
	REFERENCES HR_USER(USERID) );
