/*********************************************************

	WIKIBOOK - Sequence 생성

	SQ_SA_UPLOAD 는 MINVALUE 1 MAXVALUE 90000000 START WITH 1 CYCLE 옵션으로 생성한다.

	Oracle RAC 구성일 경우 반드시 ORDER 옵션을 추가하여 생성한다.
	
*********************************************************/
-- SELECT 'CREATE SEQUENCE '||SEQUENCE_NAME||' INCREMENT BY 1 START WITH 1 '||DECODE(CYCLE_FLAG, 'Y', 'MAXVALUE 99999999 CYCLE', '')||'; ' Q  FROM USER_SEQUENCES;

CREATE SEQUENCE SQ_WIKIBOOK 			INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SQ_WIKIBOOK_OPN 		INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SQ_WIKIBOOK_COMMENT 	INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SQ_WIKIBOOK_ITEM 		INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SQ_WIKIBOOK_ITEM_FILE 	INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SQ_WIKIBOOK_FVRT		INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SQ_WIKIBOOK_ITEM_RFRN 	INCREMENT BY 1 START WITH 1 ;