/*************************************************
	
	코멘트
	
SELECT 'COMMENT ON TABLE '||TABLE_NAME||' IS '''||COMMENTS||'''; ' Q FROM USER_TAB_COMMENTS
WHERE TABLE_NAME NOT LIKE 'BIN%'
AND TABLE_NAME NOT LIKE 'VW_%'
ORDER BY TABLE_NAME;

SELECT 'COMMENT ON COLUMN '||TABLE_NAME||'.'||COLUMN_NAME||' IS '''||COMMENTS||'''; ' Q FROM USER_COL_COMMENTS
WHERE TABLE_NAME NOT LIKE 'BIN%'
AND TABLE_NAME NOT LIKE 'VW_%'
ORDER BY TABLE_NAME, COLUMN_NAME;

*************************************************/
 

COMMENT ON TABLE WIKIBOOK IS '위키북' ;
COMMENT ON COLUMN WIKIBOOK.APLY_DATE IS '신청일시' ;
COMMENT ON COLUMN WIKIBOOK.BOOKID IS '위키북일련번호' ;
COMMENT ON COLUMN WIKIBOOK.BOOK_INTRO IS '위키북소개' ;
COMMENT ON COLUMN WIKIBOOK.CATH_CNT IS '참여저자수' ;
COMMENT ON COLUMN WIKIBOOK.ISVISB IS '보임여부' ;
COMMENT ON COLUMN WIKIBOOK.ITEM_CNT IS '등록글수' ;
COMMENT ON COLUMN WIKIBOOK.KMID IS '지식맵일련번호' ;
COMMENT ON COLUMN WIKIBOOK.LAST_UPDT IS '마지막수정일시' ;
COMMENT ON COLUMN WIKIBOOK.LEVEL1 IS '레벨1' ;
COMMENT ON COLUMN WIKIBOOK.LEVEL2 IS '레벨2' ;
COMMENT ON COLUMN WIKIBOOK.LEVEL3 IS '레벨3' ;
COMMENT ON COLUMN WIKIBOOK.LEVEL4 IS '레벨4' ;
COMMENT ON COLUMN WIKIBOOK.PICT_SAVE_CODE IS '사진저장코드' ;
COMMENT ON COLUMN WIKIBOOK.PICT_SAVE_PATH IS '사진저장경로' ;
COMMENT ON COLUMN WIKIBOOK.RGST_DATE IS '등록일시' ;
COMMENT ON COLUMN WIKIBOOK.SCRT_LEVEL IS '보안등급' ;
COMMENT ON COLUMN WIKIBOOK.STATUS IS '상태' ;
COMMENT ON COLUMN WIKIBOOK.THUMB_SAVE_CODE IS '썸네일저장코드' ;
COMMENT ON COLUMN WIKIBOOK.THUMB_SAVE_PATH IS '썸네일저장경로' ;
COMMENT ON COLUMN WIKIBOOK.TITLE IS '제목' ;
COMMENT ON COLUMN WIKIBOOK.UPDT_NAME IS '목차수정자이름' ;
COMMENT ON COLUMN WIKIBOOK.UPDT_USERID IS '목차수정자일련번호' ;
COMMENT ON COLUMN WIKIBOOK.USERID IS '사용자일련번호' ;
COMMENT ON COLUMN WIKIBOOK.USER_DISP IS '사용자상세이름' ;
COMMENT ON COLUMN WIKIBOOK.USER_NAME IS '사용자이름' ;
COMMENT ON COLUMN WIKIBOOK.VISIT_CNT IS '방문횟수' ;
COMMENT ON COLUMN WIKIBOOK.OPN_CNT IS '의견수' ;
COMMENT ON COLUMN WIKIBOOK.SPID IS '스페이스일련번호';
COMMENT ON COLUMN WIKIBOOK.SYMPATHY_CNT IS '공감수'; 
COMMENT ON COLUMN WIKIBOOK.ISMOBILE IS '모바일등록여부'; 
COMMENT ON COLUMN WIKIBOOK.TENANTID IS '회사별ID'; 
COMMENT ON COLUMN WIKIBOOK.MODULEID IS '모듈ID'; 
COMMENT ON COLUMN WIKIBOOK.CLASSID IS '클래스ID'; 
COMMENT ON COLUMN WIKIBOOK.APPID IS '앱일련번호' ;
COMMENT ON COLUMN WIKIBOOK.READ_CNT IS '조회수' ;

COMMENT ON TABLE WIKIBOOK_OPN IS '위키북의견' ;
COMMENT ON COLUMN WIKIBOOK_OPN.CONTENT IS '내용' ;
COMMENT ON COLUMN WIKIBOOK_OPN.GID IS '그룹일련번호' ;
COMMENT ON COLUMN WIKIBOOK_OPN.BOOKID IS '위키북일련번호' ;
COMMENT ON COLUMN WIKIBOOK_OPN.OPNID IS '의견일련번호' ;
COMMENT ON COLUMN WIKIBOOK_OPN.RGST_DATE IS '등록일시' ;
COMMENT ON COLUMN WIKIBOOK_OPN.USERID IS '사용자일련번호' ;
COMMENT ON COLUMN WIKIBOOK_OPN.USER_DISP IS '사용자상세이름' ;
COMMENT ON COLUMN WIKIBOOK_OPN.USER_NAME IS '사용자이름' ;

COMMENT ON TABLE WIKIBOOK_SCRT IS '위키북보안' ;
COMMENT ON COLUMN WIKIBOOK_SCRT.XID IS '권한확인번호' ;
COMMENT ON COLUMN WIKIBOOK_SCRT.ISCOMP IS '자동입력여부' ;
COMMENT ON COLUMN WIKIBOOK_SCRT.ISVISB IS '보임여부' ;
COMMENT ON COLUMN WIKIBOOK_SCRT.BOOKID IS '위키북일련번호' ;
COMMENT ON COLUMN WIKIBOOK_SCRT.SEQ_ORDER IS '그룹순차부여번호' ;
COMMENT ON COLUMN WIKIBOOK_SCRT.TITLE IS '제목' ;

COMMENT ON TABLE WIKIBOOK_CATH IS '위키북공동저자' ;
COMMENT ON COLUMN WIKIBOOK_CATH.BOOKID IS '위키북일련번호' ;
COMMENT ON COLUMN WIKIBOOK_CATH.SEQ_ORDER IS '그룹순차부여번호' ;
COMMENT ON COLUMN WIKIBOOK_CATH.USERID IS '사용자일련번호' ;
COMMENT ON COLUMN WIKIBOOK_CATH.USER_DISP IS '사용자상세이름' ;
COMMENT ON COLUMN WIKIBOOK_CATH.USER_NAME IS '사용자이름' ;

COMMENT ON TABLE WIKIBOOK_COMMENT IS '위키북코멘트' ;
COMMENT ON COLUMN WIKIBOOK_COMMENT.COMMENTID IS '코멘트일련번호' ;
COMMENT ON COLUMN WIKIBOOK_COMMENT.COMMENT_CODE IS '코멘트코드' ;
COMMENT ON COLUMN WIKIBOOK_COMMENT.CONTENT IS '내용' ;
COMMENT ON COLUMN WIKIBOOK_COMMENT.BOOKID IS '위키북일련번호' ;
COMMENT ON COLUMN WIKIBOOK_COMMENT.RGST_DATE IS '등록일시' ;
COMMENT ON COLUMN WIKIBOOK_COMMENT.USERID IS '사용자일련번호' ;
COMMENT ON COLUMN WIKIBOOK_COMMENT.USER_DISP IS '사용자상세이름' ;
COMMENT ON COLUMN WIKIBOOK_COMMENT.USER_NAME IS '사용자이름' ;

COMMENT ON TABLE WIKIBOOK_SYMPATHY IS '위키북공감'; 
COMMENT ON COLUMN WIKIBOOK_SYMPATHY.INST_DATE IS '입력일시'; 
COMMENT ON COLUMN WIKIBOOK_SYMPATHY.BOOKID IS '위키북일련번호'; 
COMMENT ON COLUMN WIKIBOOK_SYMPATHY.SYMP_TYPE IS '공감타입'; 
COMMENT ON COLUMN WIKIBOOK_SYMPATHY.USERID IS '사용자일련번호'; 
COMMENT ON COLUMN WIKIBOOK_SYMPATHY.USER_DISP IS '사용자상세이름'; 
COMMENT ON COLUMN WIKIBOOK_SYMPATHY.USER_NAME IS '사용자이름'; 

COMMENT ON TABLE WIKIBOOK_ITEM IS '위키북목차' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.BOOKID IS '위키북일련번호' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.CONTENT IS '내용' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.FILE_EXT IS '확장자' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.FLAG_CODE IS '상태표시코드' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.GID IS '그룹일련번호' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.ROOTID IS '최상위노드일련번호' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.PID IS '상위일련번호' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.POS IS '답변깊이' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.SORT IS '정렬순서' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.INST_DATE IS '입력일시' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.ISVISB IS '보임여부' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.ITEMID IS '일련번호' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.LAST_UPDT IS '마지막수정일시' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.OPN_CNT IS '의견수' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.READ_CNT IS '조회수' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.RGST_DATE IS '등록일시' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.STATUS IS '상태' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.TITLE IS '제목' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.USERID IS '사용자일련번호' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.USER_DISP IS '사용자상세이름' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.USER_NAME IS '사용자이름' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.VRSN_DISP IS '수정자상세이름' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.VRSN_NAME IS '수정자이름' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.VRSN_NUM IS '버전번호' ;
COMMENT ON COLUMN WIKIBOOK_ITEM.VRSN_USERID IS '수정자일련번호' ;

COMMENT ON TABLE WIKIBOOK_ITEM_FILE IS '위키북목차첨부화일' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_FILE.DNLD_CNT IS '다운로드횟수' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_FILE.FILEID IS '파일일련번호' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_FILE.FILE_NAME IS '파일이름' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_FILE.FILE_SIZE IS '파일사이즈' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_FILE.ITEMID IS '일련번호' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_FILE.SAVE_CODE IS '저장코드' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_FILE.SAVE_PATH IS '저장경로' ;

COMMENT ON TABLE WIKIBOOK_ITEM_READ IS '위키북목차읽기로그' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_READ.CMD_CODE IS '활동코드' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_READ.INST_DATE IS '입력일시' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_READ.ITEMID IS '일련번호' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_READ.STAT_FLAG IS '통계상태' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_READ.USERID IS '사용자일련번호' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_READ.USER_DISP IS '사용자상세이름' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_READ.USER_NAME IS '사용자이름' ;

COMMENT ON TABLE WIKIBOOK_ITEM_TAG IS '위키북목차태그' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_TAG .ITEMID IS '일련번호' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_TAG .ITEM_DATE IS '글작성일시' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_TAG .SEQ_ORDER IS '그룹순차부여번호' ;
COMMENT ON COLUMN WIKIBOOK_ITEM_TAG .TAG IS '태그' ;


COMMENT ON TABLE WIKIBOOK_HISTORY IS '위키북저자변경이력' ;
COMMENT ON COLUMN WIKIBOOK_HISTORY.BOOKID IS '위키북일련번호' ;
COMMENT ON COLUMN WIKIBOOK_HISTORY.NEW_USERID IS '새저자일련번호' ;
COMMENT ON COLUMN WIKIBOOK_HISTORY.NEW_USERNAME IS '새저자이름' ;
COMMENT ON COLUMN WIKIBOOK_HISTORY.NEW_USERDISP IS '새저자상세이름' ;
COMMENT ON COLUMN WIKIBOOK_HISTORY.OLD_USERID IS '이전저자일련번호' ;
COMMENT ON COLUMN WIKIBOOK_HISTORY.OLD_USERNAME IS '이전저자이름' ;
COMMENT ON COLUMN WIKIBOOK_HISTORY.OLD_USERDISP IS '이전저자상세이름' ;
COMMENT ON COLUMN WIKIBOOK_HISTORY.RGST_USERID IS '등록자일련번호' ;
COMMENT ON COLUMN WIKIBOOK_HISTORY.RGST_USERNAME IS '등록자이름' ;
COMMENT ON COLUMN WIKIBOOK_HISTORY.INST_DATE IS '입력일시' ;


COMMENT ON TABLE WIKIBOOK_FVRT IS '위키북즐겨찾기' ;
COMMENT ON COLUMN WIKIBOOK_FVRT.FVRTID IS '즐겨찾기일련번호' ;
COMMENT ON COLUMN WIKIBOOK_FVRT.BOOKID IS '위키북일련번호' ;
COMMENT ON COLUMN WIKIBOOK_FVRT.USERID IS '사용자일련번호' ;
COMMENT ON COLUMN WIKIBOOK_FVRT.RGST_DATE IS '등록일시' ;

COMMENT ON TABLE WIKIBOOK_TAG IS '위키북태그';
COMMENT ON COLUMN WIKIBOOK_TAG.ISVISB IS '보임여부'; 
COMMENT ON COLUMN WIKIBOOK_TAG.BOOKID IS '위키북일련번호'; 
COMMENT ON COLUMN WIKIBOOK_TAG.ITEM_DATE IS '글작성일시'; 
COMMENT ON COLUMN WIKIBOOK_TAG.SEQ_ORDER IS '그룹순차부여번호'; 
COMMENT ON COLUMN WIKIBOOK_TAG.TAG IS '태그';

COMMENT ON TABLE WIKIBOOK_READ IS '위키북조회로그';
COMMENT ON COLUMN WIKIBOOK_READ.CMD_CODE IS '활동코드'; 
COMMENT ON COLUMN WIKIBOOK_READ.INST_DATE IS '입력일시'; 
COMMENT ON COLUMN WIKIBOOK_READ.BOOKID IS '위키북일련번호'; 
COMMENT ON COLUMN WIKIBOOK_READ.STAT_FLAG IS '통계상태'; 
COMMENT ON COLUMN WIKIBOOK_READ.USERID IS '사용자일련번호'; 
COMMENT ON COLUMN WIKIBOOK_READ.USER_DISP IS '사용자상세이름'; 
COMMENT ON COLUMN WIKIBOOK_READ.USER_NAME IS '사용자이름';

COMMENT ON TABLE WIKIBOOK_ITEM_RFRN IS '위키북목차관련지식';
COMMENT ON COLUMN WIKIBOOK_ITEM_RFRN.APPID IS '앱일련번호'; 
COMMENT ON COLUMN WIKIBOOK_ITEM_RFRN.CLASSID IS '클래스ID'; 
COMMENT ON COLUMN WIKIBOOK_ITEM_RFRN.ITEMID IS '일련번호'; 
COMMENT ON COLUMN WIKIBOOK_ITEM_RFRN.MODULEID IS '모듈ID'; 
COMMENT ON COLUMN WIKIBOOK_ITEM_RFRN.RFRNID IS '관련지식일련번호'; 
COMMENT ON COLUMN WIKIBOOK_ITEM_RFRN.RFRN_QUERY IS '관련지식연산식'; 
COMMENT ON COLUMN WIKIBOOK_ITEM_RFRN.SPID IS '스페이스일련번호'; 
COMMENT ON COLUMN WIKIBOOK_ITEM_RFRN.TITLE IS '제목'; 
COMMENT ON COLUMN WIKIBOOK_ITEM_RFRN.USERID IS '사용자일련번호'; 
COMMENT ON COLUMN WIKIBOOK_ITEM_RFRN.USER_NAME IS '사용자이름';
COMMENT ON COLUMN WIKIBOOK_ITEM_RFRN.EXTR_APPID  IS 'Remote앱일련번호'; 
