/*
	Move CLOB Tablespace
	
SELECT 'ALTER TABLE '||TABLE_NAME||' MOVE LOB('||COLUMN_NAME||') STORE AS (TABLESPACE R6_LOB); ' QUERY
FROM USER_TAB_COLUMNS
WHERE DATA_TYPE IN ('BLOB', 'CLOB');
*/
-- MOVE LOB
ALTER TABLE WIKIBOOK_ITEM MOVE LOB(CONTENT) STORE AS (TABLESPACE R6_LOB);