WHENEVER SQLERROR EXIT FAILURE ;
ALTER TABLE GUIDE ADD(
	CONSTRAINT XPK_GUIDE PRIMARY KEY (ITEMID));
  
  
ALTER TABLE GUIDE_RELATE ADD(
	CONSTRAINT XPK_GUIDE_RELATE PRIMARY KEY (RELTID));


ALTER TABLE GUIDE_RELATE_FILE ADD(
	CONSTRAINT XPK_GUIDE_RELATE_FILE PRIMARY KEY (FILEID));

  
ALTER TABLE GUIDE_RFRN ADD(
	CONSTRAINT XPK_GUIDE_RFRN PRIMARY KEY (RFRNID));
  
    
ALTER TABLE GUIDE_OPN ADD(
	CONSTRAINT XPK_GUIDE_OPN PRIMARY KEY (OPNID));
  
  
ALTER TABLE GUIDE_HISTORY ADD(
	CONSTRAINT XPK_GUIDE_HISTORY PRIMARY KEY (HISTORYID));  
  
ALTER TABLE GUIDE_FILE ADD(
	CONSTRAINT XPK_GUIDE_FILE PRIMARY KEY (FILEID));  
	
ALTER TABLE GUIDE_REQ ADD(
	CONSTRAINT XPK_GUIDE_REQ PRIMARY KEY (REQID));	
	
ALTER TABLE GUIDE_TEMPLATE ADD(
	CONSTRAINT XPK_GUIDE_TEMPLATE PRIMARY KEY (TEMPLATEID));

ALTER TABLE GUIDE_TEMPLATE_FILE ADD(
	CONSTRAINT XPK_GUIDE_TEMPLATE_FILE PRIMARY KEY (FILEID));  
	
ALTER TABLE GUIDE_TEMPLATE_RFRN ADD(
	CONSTRAINT XPK_GUIDE_TEMPLATE_RFRN PRIMARY KEY (RFRNID));
	
ALTER TABLE GUIDE_TABLE ADD(
	CONSTRAINT XPK_GUIDE_TABLE PRIMARY KEY (TABLEID));