WHENEVER SQLERROR EXIT FAILURE ;
ALTER TABLE GUIDE ADD(
	CONSTRAINT WBCLASS_R_GUIDE FOREIGN KEY (CLASSID)
	REFERENCES WB_CLASS(CLASSID) );

ALTER TABLE GUIDE ADD(
	CONSTRAINT WBMODULE_R_GUIDE FOREIGN KEY (MODULEID)
	REFERENCES WB_MODULE(MODULEID) );

ALTER TABLE GUIDE ADD(
	CONSTRAINT TENANT_R_GUIDE FOREIGN KEY (TENANTID)
	REFERENCES TENANT(TENANTID) );

ALTER TABLE GUIDE_MAP ADD(
	CONSTRAINT GUIDE_C_MAP FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);
  
ALTER TABLE GUIDE_RELATE ADD(
	CONSTRAINT GUIDE_C_RELATE FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);

ALTER TABLE GUIDE_READ ADD(
	CONSTRAINT GUIDE_C_READ FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);

ALTER TABLE GUIDE_SCRT ADD(
	CONSTRAINT GUIDE_C_SCRT FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);

ALTER TABLE GUIDE_RFRN ADD(
	CONSTRAINT GUIDE_C_RFRN FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);

ALTER TABLE GUIDE_OPN ADD(
	CONSTRAINT GUIDE_C_OPN FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);

ALTER TABLE GUIDE_HISTORY ADD(
	CONSTRAINT GUIDE_C_HISTORY FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);

ALTER TABLE GUIDE_TAG ADD(
	CONSTRAINT GUIDE_C_TAG FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);

ALTER TABLE GUIDE_FILE ADD(
	CONSTRAINT GUIDE_C_FILE FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);

ALTER TABLE GUIDE_RELATE_FILE ADD(
	CONSTRAINT GUIDE_C_RELATE_FILE FOREIGN KEY (ITEMID)
	REFERENCES GUIDE_RELATE(RELTID) ON DELETE CASCADE);
	
ALTER TABLE GUIDE_APPR ADD(
	CONSTRAINT GUIDE_C_APPR FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);
	
ALTER TABLE GUIDE_RVWR ADD(
	CONSTRAINT GUIDE_C_RVWR FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);	
	
ALTER TABLE GUIDE_RES ADD(
	CONSTRAINT GUIDEREQ_C_RES FOREIGN KEY (REQID)
	REFERENCES GUIDE_REQ(REQID) ON DELETE CASCADE);	
	
ALTER TABLE GUIDE_CHARGE ADD(
	CONSTRAINT GUIDE_R_GUIDECHARGE FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) );	

ALTER TABLE GUIDE_TEMPLATE_FILE ADD(
	CONSTRAINT GUIDETEMPLATE_C_FILE FOREIGN KEY (TEMPLATEID)
	REFERENCES GUIDE_TEMPLATE(TEMPLATEID) ON DELETE CASCADE);
	
ALTER TABLE GUIDE_TEMPLATE_RFRN ADD(
	CONSTRAINT GUIDETEMPLATE_C_RFRN FOREIGN KEY (TEMPLATEID)
	REFERENCES GUIDE_TEMPLATE(TEMPLATEID) ON DELETE CASCADE);
	
ALTER TABLE GUIDE_RECENT ADD(
	CONSTRAINT GUIDE_C_RECENT FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);
	
ALTER TABLE GUIDE_REQ ADD(
	CONSTRAINT GUIDE_C_REQ FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);
 
ALTER TABLE GUIDE_TABLE ADD(
	CONSTRAINT GUIDE_C_TABLE FOREIGN KEY (ITEMID)
	REFERENCES GUIDE(ITEMID) ON DELETE CASCADE);