WHENEVER SQLERROR EXIT FAILURE ;
CREATE SEQUENCE SQ_GUIDE   INCREMENT BY 1 START WITH 1 ; 
CREATE SEQUENCE SQ_GUIDE_RELATE   INCREMENT BY 1 START WITH 1 ; 
CREATE SEQUENCE SQ_GUIDE_RFRN   INCREMENT BY 1 START WITH 1 ; 
CREATE SEQUENCE SQ_GUIDE_OPN   INCREMENT BY 1 START WITH 1 ; 
CREATE SEQUENCE SQ_GUIDE_HISTORY   INCREMENT BY 1 START WITH 1 ; 
CREATE SEQUENCE SQ_GUIDE_FILE   INCREMENT BY 1 START WITH 1 ; 
CREATE SEQUENCE SQ_GUIDE_RELATE_FILE   INCREMENT BY 1 START WITH 1 ; 
CREATE SEQUENCE SQ_GUIDE_REQ INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE SQ_GUIDE_RECENT INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SQ_GUIDE_TEMPLATE INCREMENT BY 1 START WITH 1 ; 

CREATE SEQUENCE SQ_GUIDE_TEMPLATE_FILE INCREMENT BY 1 START WITH 1 ; 
CREATE SEQUENCE SQ_GUIDE_TEMPLATE_RFRN INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE SQ_GUIDE_TABLE   INCREMENT BY 1 START WITH 1 ; 