CREATE TABLE MB_ITEM_LIKE 
 ( 
 LIKEID NUMBER(8,0) NOT NULL ENABLE, 
	USERID NUMBER(8,0) NOT NULL ENABLE, 
  OPNID NUMBER(8,0) NOT NULL ENABLE,
	INST_DATE DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINTs "XPK_MB_ITEM_LIKE" PRIMARY KEY ("LIKEID"));
	 
	 
CREATE sequence SQ_MB_ITEM_LIKE
 INCREMENT BY 1 START WITH 1;	 
 
ALTER TABLE mb_item_opn ADD like_cnt number(8,0) DEFAULT 0 not null;
